### ISSUE TITLE
OAuth:Unauthorized (401)

### ISSUE THREAD

**Issue by listenlight** [jrallison/authlogic_oauth#15]
I found a blog post that said to change the before_filter but that is not working.  I keep getting this error.  Please help.  I can find no other help on this.

<pre><code>
OAuth::Unauthorized (401 Unauthorized):
  oauth (0.4.0) lib/oauth/consumer.rb:215:in `token_request'
  oauth (0.4.0) lib/oauth/consumer.rb:136:in `get_request_token'
  /usr/lib/ruby/gems/1.8/gems/authlogic-oauth-1.0.8/lib/authlogic_oauth/oauth_process.rb:21:in `redirect_to_oauth'
  /usr/lib/ruby/gems/1.8/gems/authlogic-oauth-1.0.8/lib/authlogic_oauth/acts_as_authentic.rb:63:in `save'
  app/controllers/users_controller.rb:11:in `create'
  haml (2.2.24) rails/./lib/sass/plugin/rails.rb:20:in `process'
  /usr/lib/ruby/gems/1.8/gems/authlogic-oauth-1.0.8/lib/oauth_callback_filter.rb:10:in `call'
  /usr/lib/ruby/gems/1.8/gems/authlogic-oauth-1.0.8/lib/oauth_callback_filter.rb:10:in `call'
</code></pre>

**Comment by madhums** [comment]
i have got the same problem too...

**Comment by madhums** [comment]
i figured it out... you should give the proper token and secret values in the Oauth::consumer function...
