### ISSUE TITLE
 `method_missing': undefined method `add_acts_as_authentic_module' for ActiveRecord::Base:Class (NoMethodError)

### ISSUE THREAD

**Issue by aac** [jrallison/authlogic_oauth#9]
Getting this error from script/generate migration foo:

/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/base.rb:1959:in `method_missing': undefined method`add_acts_as_authentic_module' for ActiveRecord::Base:Class (NoMethodError)
    from /usr/lib/ruby/gems/1.8/gems/authlogic-oauth-1.0.8/lib/authlogic_oauth/acts_as_authentic.rb:6:in `included'
    from /usr/lib/ruby/gems/1.8/gems/authlogic-oauth-1.0.8/lib/authlogic_oauth/acts_as_authentic.rb:4:in`class_eval'
    from /usr/lib/ruby/gems/1.8/gems/authlogic-oauth-1.0.8/lib/authlogic_oauth/acts_as_authentic.rb:4:in `included'
    from /usr/lib/ruby/gems/1.8/gems/authlogic-oauth-1.0.8/lib/authlogic_oauth.rb:7:in`include'
    from /usr/lib/ruby/gems/1.8/gems/authlogic-oauth-1.0.8/lib/authlogic_oauth.rb:7:in `send'
    from /usr/lib/ruby/gems/1.8/gems/authlogic-oauth-1.0.8/lib/authlogic_oauth.rb:7
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in`require'
    from /usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in `new_constants_in'
    from /usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in`require'
    from /usr/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/rails/gem_dependency.rb:208:in `load'
    from /usr/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:307:in`load_gems'
    from /usr/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:307:in `each'
    from /usr/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:307:in`load_gems'
    from /usr/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:164:in `process'
    from /usr/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:113:in`send'
    from /usr/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:113:in `run'
    from /home/andrew/Workspace/follower/robin/config/environment.rb:9
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /usr/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/commands/generate.rb:1
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from script/generate:3

**Comment by aac** [comment]
Nevermind, I'm a dumbass.
